name: color_bootcamp
description: Color BootCamp.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.1

  shared_preferences: ^0.5.12+4
  enum_to_string: ^1.0.14

  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0

  build_runner:
  freezed:

flutter:
  uses-material-design: true
