name: color_bootcamp
description: Color BootCamp.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  freezed_annotation: ^2.0.0

  flutter_riverpod: ^1.0.0
  state_notifier: ^0.7.0

  hive: ^2.0.0
  hive_flutter: ^1.0.0

  go_router: ^4.0.0
  google_fonts: ^3.0.0
  shared_preferences: ^2.0.0

  breakpoints_mq: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.0.0
  freezed: ^2.0.0
  hive_generator: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/OFL.txt
