name: color_bootcamp
description: Color BootCamp.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0

  shared_preferences: ^2.0.0
  enum_to_string: ^2.0.0

  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart:

  build_runner:
  freezed:

flutter:
  uses-material-design: true
