name: color_bg
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.14.0
  hooks_riverpod: ^0.12.1

  shared_preferences: ^0.5.12+4
  enum_to_string: ^1.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.0.0

flutter:
  uses-material-design: true
